"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['mixit.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'frameworks': [
        '/usr/local/Cellar/ffmpeg/3.4/bin/ffmpeg',
        '/usr/local/Cellar/ffmpeg/3.4/bin/ffprobe'
    ],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
